sudo: false
cache: apt
language: cpp
compiler:
  - g++
  - clang++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - llvm-toolchain-precise
    packages:
      - clang-3.8
      - g++-6
      - gcc-6
install:
  - if [ "$CXX" = 'g++' ]; then export CXX='g++-6'; fi
  - if [ "$CXX" = 'clang++' ]; then export CXX='clang++-3.8'; fi
script: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER="$CXX" && make && others/MsdnCpuId/MsdnCpuId
