version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
build_script:
- cmd: >-
    mkdir build

    cd build

    cmake .. -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles"

    nmake /nologo
test_script:
- cmd: '"others\MsdnCpuId\MsdnCpuId.exe"'
